services:

  # InfluxDB timeseries database
  influxdb:
    container_name: influxdb
    image: influxdb:latest
    volumes: 
      - ./influx:/var/lib/influxdb2
      - ./influx/config.yaml:/etc/influxdb2/config.yml
      - ./influx:/docker-entrypoint-initdb.d
    ports:
     - 8086:8086
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUX_NODE_USER}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUX_NODE_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUX_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUX_BUCKET}
      - INFLUX_ADMIN_USER=${INFLUX_NODE_USER}
      - INFLUX_ADMIN_PASSWORD=${INFLUX_NODE_PASSWORD}

  # NGINX reverse proxy
  nginx:
    image: nginx:alpine
    ports:
     - 80:80
     - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

  # IRC server for supporting communications
  ircd:
    image: inspircd/inspircd-docker:latest
    volumes:
      - ./inspircd.conf:/inspircd/conf/inspircd.conf
    ports:
      - 6667:6667
      - 7001:7001
    environment:
    # - INSP_CONNECT_PASSWORD=${COMMUNICATIONS_MASTER_PASSWORD}
      - INSP_NET_SUFFIX=${IRC_SERVER_SUFFIX}
      - INSP_ENABLE_DNSBL=no
